version: "3.10"

services:
  web:
    build: ./django_app
    volumes:
      - ./photos:/app/photos
      - ./.env:/app/.env
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  bot:
    build: ./aiogram_bot
    volumes:
      - ./photos:/app/photos
      - ./.env:/app/.env
      - ./logs:/app/logs
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
